name: exom
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.4
  - colorama=0.4.6
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - filelock=3.13.1
  - fsspec=2024.6.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - importlib-metadata=8.2.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - ld_impl_linux-64=2.38
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.1.7
  - libcurand=10.3.6.82
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - lightning=2.3.3
  - lightning-utilities=0.11.6
  - llvm-openmp=14.0.6
  - markdown=3.6
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.14
  - packaging=24.1
  - pip=24.0
  - protobuf=3.20.3
  - pydeprecate=0.3.2
  - python=3.11.9
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - pytorch-lightning=1.7.7
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.14
  - torchmetrics=1.4.0.post0
  - torchtriton=3.0.0
  - tqdm=4.66.4
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zipp=3.19.2
  - zlib=1.2.13
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.53.1
      - kiwisolver==1.4.5
      - matplotlib==3.9.1
      - pandas==2.2.2
      - pillow==10.4.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - seaborn==0.13.2
      - tueplots==0.0.15
      - tzdata==2024.1
      - zuko==1.1.0
